name: Execute Script on EC2
'on':
  - push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Execute script on EC2
        env:
          PRIVATE_KEY: '${{ secrets.EC2_SSH_PRIVATE_KEY }}'
          HOST: 18.223.21.115
          USER: ec2-user
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key

          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} 'npm
          run test'
