name: Run tests with Playwright
'on':
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 'Set up Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v2
        with:
          node-version: '${{ matrix.node-version }}'
      - name: Install dependencies
        run: |
          npm ci
          npx playwright install
      - name: Run tests
        run: npm run test

